1           = "https://eth.drpc.org"                                                  # ethereum
10          = "https://optimism.drpc.org"                                             # optimism
14          = "https://flare.rpc.thirdweb.com"                                        # flare
25          = "https://evm.cronos.org"                                                # cronosevm
37          = "https://dimension-evm-rpc.xpla.dev"                                    # xpla
40          = "https://mainnet.telos.net/evm"                                         # telos
47          = "https://cube-evm-rpc.xpla.dev"                                         # xpla-testnet
56          = "https://bsc.drpc.org"                                                  # bsc
66          = "https://exchainrpc.okex.org"                                           # okx
71          = "https://evmtestnet.confluxrpc.com"                                     # conflux-testnet
83          = "https://rpctest.meter.io"                                              # meter-testnet
97          = "https://data-seed-prebsc-1-s3.binance.org:8545"                        # bsc-testnet
100         = "https://gnosis.drpc.org"                                               # gnosis
122         = "https://rpc.fuse.io"                                                   # fuse
123         = "https://rpc.fusespark.io"                                              # fusespark
137         = "https://polygon.drpc.org"                                              # polygon
169         = "https://pacific-rpc.manta.network/http"                                # manta
195         = "https://testrpc.xlayer.tech"                                           # xlayer-testnet
196         = "https://rpc.xlayer.tech"                                               # xlayer
204         = "https://opbnb-mainnet-rpc.bnbchain.org"                                # opbnb
240         = "https://testnet.zkevm.cronos.org"                                      # cronoszkevm-testnet
250         = "https://fantom.drpc.org"                                               # fantom
252         = "https://rpc.frax.com"                                                  # fraxtal
291         = "https://rpc.orderly.network"                                           # orderly
295         = "https://mainnet.hashio.io/api"                                         # hedera
296         = "https://testnet.hashio.io/api"                                         # hedera-testnet
300         = "https://zksync-sepolia.drpc.org"                                       # zksync-sepolia
324         = "https://zksync.drpc.org"                                               # zksync
335         = "https://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/rpc"      # dfk-testnet
478         = "https://rpc.form.network/infra-partner-http"                           # form-testnet
480         = "https://worldchain-mainnet.g.alchemy.com/public"                       # worldchain
592         = "https://evm.astar.network"                                             # astar
747         = "https://mainnet.evm.nodes.onflow.org"                                  # flow
919         = "https://sepolia.mode.network"                                          # mode-testnet
1030        = "https://evm.confluxrpc.com"                                            # conflux
1075        = "https://json-rpc.evm.iotaledger.net"                                   # iota-testnet
1088        = "https://andromeda.metis.io/?owner=1088"                                # metis
1101        = "https://zkevm-rpc.com"                                                 # zkevm
1115        = "https://rpc.test.btcs.network/"                                        # coredao-testnet
1116        = "https://rpc.coredao.org/"                                              # coredao
1135        = "https://rpc.api.lisk.com"                                              # lisk
1284        = "https://rpc.api.moonbeam.network"                                      # moonbeam
1285        = "https://rpc.api.moonriver.moonbeam.network"                            # moonriver
1287        = "https://rpc.api.moonbase.moonbeam.network"                             # moonbase
1329        = "https://evm-rpc.sei-apis.com"                                          # sei
1480        = "https://rpc.vana.org"                                                  # islander
1625        = "https://rpc.gravity.xyz"                                               # gravity
1891        = "https://replicator.pegasus.lightlink.io/rpc/v1"                        # lightlink-testnet
1923        = "https://rpc.ankr.com/swell"                                            # swell
1946        = "https://rpc.minato.soneium.org/"                                       # minato-testnet
1992        = "https://sanko-arb-sepolia.rpc.caldera.xyz/http"                        # sanko-testnet
1996        = "https://mainnet.sanko.xyz"                                             # sanko
2038        = "https://subnets.avax.network/shrapnel/testnet/rpc"                     # shrapnel-testnet
2044        = "https://subnets.avax.network/shrapnel/mainnet/rpc"                     # shrapnel
2221        = "https://evm.testnet.kava.io"                                           # kava-testnet
2222        = "https://evm.kava.io"                                                   # kava
2345        = "https://rpc.goat.network"                                              # goat
2442        = "https://rpc.cardona.zkevm-rpc.com"                                     # zkpolygon-sepolia
2522        = "https://rpc.testnet.frax.com"                                          # fraxtal-testnet
2525        = "https://mainnet.rpc.inevm.com/http"                                    # bb1
2810        = "https://rpc-holesky.morphl2.io"                                        # morph-testnet
2818        = "https://rpc.morphl2.io"                                                # morph
3636        = "https://node.botanixlabs.dev"                                          # botanix-testnet
3939        = "https://test.doschain.com"                                             # dos-testnet
4002        = "https://rpc.testnet.fantom.network/"                                   # fantom-testnet
4200        = "https://merlin.blockpi.network/v1/rpc/public"                          # merlin
4337        = "https://subnets.avax.network/beam/mainnet/rpc"                         # beam
4801        = "https://worldchain-sepolia.g.alchemy.com/public"                       # worldcoin-testnet
5000        = "https://rpc.mantle.xyz"                                                # mantle
5115        = "https://rpc.testnet.citrea.xyz"                                        # citrea-testnet
5611        = "https://opbnb-testnet-rpc.bnbchain.org"                                # opbnb-testnet
6001        = "https://fullnode-mainnet.bouncebitapi.com"                             # bouncebit
6342        = "https://carrot.megaeth.com/rpc"                                        # megaeth-testnet
7560        = "https://cyber.alt.technology"                                          # cyber
7979        = "https://main.doschain.com"                                             # dos
8217        = "https://klaytn-pokt.nodies.app"                                        # klaytn
8453        = "https://base.drpc.org"                                                 # base
8822        = "https://json-rpc.evm.iotaledger.net"                                   # iota
10200       = "https://rpc.chiadochain.net"                                           # chiado
11501       = "https://rpc-mainnet-1.bevm.io/"                                        # bevm
13337       = "https://subnets.avax.network/beam/testnet/rpc"                         # beam-testnet
14800       = "https://rpc.moksha.vana.org"                                           # moksha-testnet
17000       = "https://ethereum-holesky.publicnode.com"                               # holesky-testnet
19011       = "https://rpc.mainnet.oasys.homeverse.games"                             # homeverse
33111       = "https://curtis.rpc.caldera.xyz/http"                                   # curtis-testnet
34443       = "https://mainnet.mode.network"                                          # mode
40875       = "https://rpc.testnet.oasys.homeverse.games"                             # homeverse-testnet
41923       = "https://rpc.edu-chain.raas.gelato.cloud"                               # edu
42161       = "https://arbitrum.drpc.org"                                             # arbitrum
42170       = "https://arbitrum-nova.drpc.org"                                        # nova
42220       = "https://celo.drpc.org"                                                 # celo
42793       = "https://node.mainnet.etherlink.com"                                    # etherlink
43113       = "https://api.avax-test.network/ext/bc/C/rpc"                            # fuji
43114       = "https://avalanche.drpc.org"                                            # avalanche
44787       = "https://alfajores-forno.celo-testnet.org"                              # alfajores
48900       = "https://zircuit-mainnet.drpc.org"                                      # zircuit
53935       = "https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc"              # dfk
55244       = "https://rpc.superposition.so"                                          # superposition
59141       = "https://rpc.sepolia.linea.build"                                       # lineasep-testnet
59144       = "https://rpc.linea.build"                                               # linea
59902       = "https://sepolia.metisdevops.link"                                      # metissep-testnet
60808       = "https://rpc.gobob.xyz"                                                 # bob
64002       = "https://xchain-testnet-rpc.idex.io"                                    # xchain-testnet
80002       = "https://polygon-amoy.drpc.org"                                         # amoy-testnet
81457       = "https://rpc.blast.io"                                                  # blast
84532       = "https://sepolia.base.org"                                              # base-sepolia
94524       = "https://xchain-rpc.idex.io"                                            # xchain
98865       = "https://rpc-plume-mainnet-0.t.conduit.xyz"                             # plume
98985       = "https://testnet-rpc.superposition.so"                                  # superposition-testnet
128123      = "https://node.ghostnet.etherlink.com"                                   # etherlink-testnet
167000      = "https://rpc.taiko.xyz"                                                 # taiko
167009      = "https://rpc.hekla.taiko.xyz"                                           # taiko-testnet
200901      = "https://rpc.bitlayer.org"                                              # bitlayer
421614      = "https://sepolia-rollup.arbitrum.io/rpc"                                # arbitrum-sepolia
534351      = "https://sepolia-rpc.scroll.io"                                         # scroll-testnet
534352      = "https://rpc.scroll.io"                                                 # scroll
660279      = "https://xai-chain.net/rpc"                                             # xai
686868      = "https://testnet-rpc.merlinchain.io"                                    # merlin-testnet
713715      = "https://evm-rpc-arctic-1.sei-apis.com"                                 # sei-testnet
743111      = "https://testnet.rpc.hemi.network/rpc"                                  # hemi-testnet
7777777     = "https://rpc.zora.energy/"                                              # zora
11155111    = "https://sepolia.drpc.org"                                              # sepolia
11155420    = "https://sepolia.optimism.io"                                           # optimism-sepolia
21000000    = "https://maizenet-rpc.usecorn.com"                                      # mp1
111557560   = "https://cyber-testnet.alt.technology"                                  # cyber-testnet
168587773   = "https://sepolia.blast.io"                                              # blast-testnet
531050104   = "https://rpc.testnet.sophon.xyz"                                        # sophon-testnet
666666666   = "https://rpc.degen.tips"                                                # degen
999999999   = "https://sepolia.rpc.zora.energy"                                       # zora-sepolia
1313161554  = "https://aurora.drpc.org"                                               # aurora
1313161555  = "https://testnet.aurora.dev/"                                           # aurora-testnet
1380012617  = "https://mainnet.rpc.rarichain.org/http"                                # rarible
1444673419  = "https://testnet.skalenodes.com/v1/juicy-low-small-testnet"             # skale-testnet
37714555429 = "https://testnet-v2.xai-chain.net/rpc"                                  # xai-testnet
