[rpc_endpoints]
ethereum = ["https://eth.drpc.org","https://ethereum.publicnode.com","https://eth-mainnet.public.blastapi.io","https://eth.llamarpc.com/rpc/${LLAMANODES_API_KEY}","https://cloudflare-eth.com","https://eth-mainnet.alchemyapi.io/v2/84tGz8xVIWFkagsaSzNjObh7aSPbxeXD","https://eth-mainnet.alchemyapi.io/v2/VsPzIezK0AtqsnrWAuV0Gew-MS7H_E5E","https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}","https://mainnet.infura.io/v3/${INFURA_API_KEY}","https://eth-pokt.nodies.app"]
optimism = ["https://optimism.drpc.org","https://mainnet.optimism.io","https://opt-mainnet.g.alchemy.com/v2/3glkhRJRgzHCB2NbDwiQa7G_FTdqn3-T","https://opt-mainnet.g.alchemy.com/v2/7urLa-8k2RR_UYc0exh-b0qg4xySL5KA","https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}","https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://op-pokt.nodies.app"]
flare = ["https://flare.rpc.thirdweb.com","https://rpc.ankr.com/flare"]
cronosevm = ["https://evm.cronos.org","https://evm-dev.cronos.org"]
xpla = https://dimension-evm-rpc.xpla.dev
telos = https://mainnet.telos.net/evm
telos-testnet = https://testnet.telos.net/evm
xpla-testnet = https://cube-evm-rpc.xpla.dev
bsc = ["https://bsc.drpc.org","https://bscrpc.com","https://binance.nodereal.io","https://bsc-dataseed.binance.org","https://bsc-dataseed1.binance.org","https://bsc-dataseed2.binance.org","https://bsc-dataseed3.binance.org","https://bsc-dataseed4.binance.org","https://bsc-pokt.nodies.app"]
okx = https://exchainrpc.okex.org
conflux-testnet = https://evmtestnet.confluxrpc.com
joc = ["https://rpc-2.japanopenchain.org:8545","https://rpc-1.japanopenchain.org:8545"]
astar-testnet = ["https://rpc-1.japanopenchain.org:8545","https://rpc-2.japanopenchain.org:8545"]
meter = https://rpc.meter.io
meter-testnet = https://rpctest.meter.io
tomo = https://rpc.tomochain.com
bsc-testnet = ["https://data-seed-prebsc-1-s3.binance.org:8545","https://data-seed-prebsc-2-s2.binance.org:8545","https://data-seed-prebsc-1-s1.binance.org:8545","https://data-seed-prebsc-1-s2.binance.org:8545","https://data-seed-prebsc-2-s1.binance.org:8545"]
gnosis = ["https://gnosis.drpc.org","https://rpc.gnosischain.com","https://rpc.ankr.com/gnosis","https://gnosis-pokt.nodies.app","https://gnosis-mainnet.public.blastapi.io","wss://rpc.gnosischain.com/wss"]
bob-testnet = https://testnet.rpc.gobob.xyz
fuse = ["https://rpc.fuse.io","https://fuse-pokt.nodies.app"]
fusespark = https://rpc.fusespark.io
polygon = ["https://polygon.drpc.org","https://matic-mainnet.chainstacklabs.com","https://polygon-rpc.com","https://polygon.llamarpc.com/rpc/${LLAMANODES_API_KEY}","https://polygon-mainnet.g.alchemy.com/v2/me6Q04fTd2kTT74BUYAp82d_3KL-ObCw","https://polygon-mainnet.g.alchemy.com/v2/q3f-QpPeM_g7rL3G21Cr9tFeuYAquyYl","https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://polygon-pokt.nodies.app","https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"]
shimmer = https://json-rpc.evm.shimmer.network
tenet-testnet = https://rpc.testnet.tenet.org
manta = https://pacific-rpc.manta.network/http
xlayer-testnet = https://testrpc.xlayer.tech
xlayer = https://rpc.xlayer.tech
opbnb = ["https://opbnb.drpc.org","https://opbnb-mainnet-rpc.bnbchain.org","https://opbnb.publicnode.com","wss://opbnb.publicnode.com"]
cronoszkevm-testnet = ["https://testnet.zkevm.cronos.org","https://seed.testnet.zkevm.cronos.org"]
fantom = ["https://fantom.drpc.org","https://rpc.ftm.tools","https://rpc2.fantom.network","https://rpc3.fantom.network","https://fantom-pokt.nodies.app"]
fraxtal = https://rpc.frax.com
orderly = ["https://rpc.orderly.network","https://l2-orderly-mainnet-0.t.conduit.xyz"]
hedera = https://mainnet.hashio.io/api
hedera-testnet = https://testnet.hashio.io/api
zksync-sepolia = ["https://zksync-sepolia.drpc.org","https://sepolia.era.zksync.dev","https://zksync-era-sepolia.blockpi.network/v1/rpc/public"]
zksync = ["https://zksync.drpc.org","https://mainnet.era.zksync.io"]
dfk-testnet = https://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/rpc
cronosevm-testnet = ["https://evm-t3.cronos.org","https://evm-dev-t3.cronos.org"]
cronoszkevm = ["https://mainnet.zkevm.cronos.org","https://seed.zkevm.cronos.org"]
form-testnet = https://rpc.form.network/infra-partner-http
worldchain = https://worldchain-mainnet.g.alchemy.com/public
astar = ["https://evm.astar.network","https://astar.public.blastapi.io"]
flow = https://mainnet.evm.nodes.onflow.org
mode-testnet = https://sepolia.mode.network
klaytn-baobab = https://api.baobab.klaytn.net:8651
conflux = https://evm.confluxrpc.com
iota-testnet = https://json-rpc.evm.iotaledger.net
metis = ["https://andromeda.metis.io/?owner=1088","https://metis.drpc.org","https://metis-pokt.nodies.app"]
zkevm = ["https://zkevm-rpc.com","https://polygon-zkevm.drpc.org"]
coredao-testnet = https://rpc.test.btcs.network/
coredao = ["https://rpc.coredao.org/","https://rpc-core.icecreamswap.com"]
lisk = ["https://rpc.api.lisk.com","https://lisk.drpc.org"]
moonbeam = ["https://rpc.api.moonbeam.network","wss://wss.api.moonbeam.network"]
moonriver = ["https://rpc.api.moonriver.moonbeam.network","wss://wss.api.moonriver.moonbeam.network"]
moonbase = ["https://rpc.api.moonbase.moonbeam.network","wss://wss.api.moonbase.moonbeam.network"]
glue = https://mainnet-node.m9.glue.net
glue-testnet = https://testnet-node-1.server-1.glue.net
sei = https://evm-rpc.sei-apis.com
islander = ["https://rpc.islander.vana.org","https://rpc.vana.org"]
tenet = https://rpc.tenet.org
gravity = https://rpc.gravity.xyz
eon-testnet = ["https://gobi-rpc.horizenlabs.io/ethv1","https://rpc.ankr.com/horizen_gobi_testnet"]
lif3-testnet = https://testnet-evm.lif3.com
lightlink-testnet = ["https://replicator.pegasus.lightlink.io/rpc/v1","https://endpoints.omniatech.io/v1/lightlink/pegasus/public"]
swell = ["https://rpc.ankr.com/swell","https://swell-mainnet.alt.technology"]
minato-testnet = https://rpc.minato.soneium.org/
sanko-testnet = https://sanko-arb-sepolia.rpc.caldera.xyz/http
sanko = https://mainnet.sanko.xyz
kiwi-testnet = https://subnets.avax.network/kiwi/testnet/rpc
shrapnel-testnet = https://subnets.avax.network/shrapnel/testnet/rpc
shrapnel = https://subnets.avax.network/shrapnel/mainnet/rpc
kava-testnet = ["https://evm.testnet.kava.io","wss://wevm.testnet.kava.io"]
kava = ["https://kava.drpc.org","https://evm.kava.io","https://evm2.kava.io","wss://wevm.kava.io","wss://wevm2.kava.io","https://kava-pokt.nodies.app"]
goat = https://rpc.goat.network
zkpolygon-sepolia = ["https://polygon-zkevm-cardona.blockpi.network/v1/rpc/public","https://rpc.cardona.zkevm-rpc.com"]
fraxtal-testnet = https://rpc.testnet.frax.com
bb1 = https://mainnet.rpc.inevm.com/http
bahamut-testnet = https://rpc1.ocean.bahamut.io
abstract = https://api.raas.matterhosted.dev
morph-testnet = https://rpc-holesky.morphl2.io
morph = https://rpc.morphl2.io
botanix-testnet = https://node.botanixlabs.dev
botanix = https://rpc.btxtestchain.com
dos-testnet = https://test.doschain.com
fantom-testnet = ["https://rpc.testnet.fantom.network/","https://rpc.ankr.com/fantom_testnet","https://fantom-testnet.public.blastapi.io"]
merlin = ["https://merlin.blockpi.network/v1/rpc/public","https://rpc.merlinchain.io"]
beam = https://subnets.avax.network/beam/mainnet/rpc
orderly-testnet = https://l2-orderly-l2-4460-sepolia-8tc3sd7dvy.t.conduit.xyz
worldcoin-testnet = https://worldchain-sepolia.g.alchemy.com/public
mantle = ["https://rpc.mantle.xyz","https://mantle.drpc.org","https://mantle.publicnode.com"]
citrea-testnet = https://rpc.testnet.citrea.xyz
opbnb-testnet = https://opbnb-testnet-rpc.bnbchain.org
bouncebit = https://fullnode-mainnet.bouncebitapi.com
megaeth-testnet = https://carrot.megaeth.com/rpc
cyber = ["https://cyber.alt.technology","https://rpc.cyber.co"]
canto = ["https://canto.slingshot.finance","https://canto.neobase.one","https://mainnode.plexnode.org:8545"]
canto-testnet = https://testnet-archive.plexnode.wtf
dos = https://main.doschain.com
klaytn = ["https://public-node-api.klaytnapi.com/v1/cypress","https://klaytn-pokt.nodies.app"]
space = https://subnets.avax.network/space/mainnet/rpc
base = ["https://base.drpc.org","https://mainnet.base.org","https://base.meowrpc.com","https://base-pokt.nodies.app","https://base.blockpi.network/v1/rpc/public"]
iota = https://json-rpc.evm.iotaledger.net
joc-testnet = ["https://rpc-1.testnet.japanopenchain.org:8545","https://rpc-2.testnet.japanopenchain.org:8545"]
chiado = ["https://rpc.chiadochain.net","https://rpc.chiado.gnosis.gateway.fm","wss://rpc.chiadochain.net/wss","https://gnosis-chiado.publicnode.com","wss://gnosis-chiado.publicnode.com"]
gameswift-testnet = ["https://rpc-gs-testnet.gameswift.io","https://rpc-testnet.gameswift.io"]
bevm = ["https://rpc-mainnet-1.bevm.io/","https://rpc-mainnet-2.bevm.io/"]
beam-testnet = https://subnets.avax.network/beam/testnet/rpc
moksha-testnet = https://rpc.moksha.vana.org
holesky-testnet = ["https://rpc.holesky.ethpandaops.io","https://ethereum-holesky.publicnode.com","wss://ethereum-holesky.publicnode.com"]
unreal-testnet = https://rpc.unreal-orbit.gelato.digital
homeverse = https://rpc.mainnet.oasys.homeverse.games
curtis-testnet = https://curtis.rpc.caldera.xyz/http
mode = ["https://mainnet.mode.network","https://1rpc.io/mode"]
homeverse-testnet = https://rpc.testnet.oasys.homeverse.games
edu = https://rpc.edu-chain.raas.gelato.cloud
arbitrum = ["https://arbitrum.drpc.org","https://arb1.arbitrum.io/rpc","https://arb-mainnet.g.alchemy.com/v2/N71NRfHZGk2jbnDkW-GiM6fTe6ysJOmp","https://arb-mainnet.g.alchemy.com/v2/KhVdIItVH0ttiQvBYYO5NPL-De-gLWoW","https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}","https://arb-pokt.nodies.app"]
nova = ["https://arbitrum-nova.drpc.org","https://nova.arbitrum.io/rpc"]
celo = ["https://celo.drpc.org","https://forno.celo.org","wss://forno.celo.org/ws"]
etherlink = ["https://node.mainnet.etherlink.com","https://etherlink-mainnet-pub-l5p9tu.zeeve.net/rpc"]
fuji = ["https://api.avax-test.network/ext/bc/C/rpc","https://rpc.ankr.com/avalanche_fuji"]
avalanche = ["https://avalanche.drpc.org","https://api.avax.network/ext/bc/C/rpc","https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}","https://avax-pokt.nodies.app/ext/bc/C/rpc"]
alfajores = ["https://alfajores-forno.celo-testnet.org","wss://alfajores-forno.celo-testnet.org/ws"]
zircuit-testnet = https://zircuit1.p2pify.com
zircuit = ["https://zircuit-mainnet.drpc.org","https://mainnet.aurora.dev"]
dfk = https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc
superposition = https://rpc.superposition.so
lineasep-testnet = ["https://linea-sepolia.blockpi.network/v1/rpc/public","https://rpc.sepolia.linea.build","https://linea-sepolia.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"]
linea = ["https://linea.drpc.org","https://rpc.linea.build","wss://rpc.linea.build","https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}","wss://linea-mainnet.infura.io/ws/v3/${INFURA_API_KEY}"]
metissep-testnet = https://sepolia.metisdevops.link
bob = ["https://rpc.gobob.xyz","https://bob-mainnet.blastapi.io/278bd36b-e02e-4391-a2b6-54e68e6695fd"]
xchain-testnet = https://xchain-testnet-rpc.idex.io
amoy-testnet = ["https://rpc.ankr.com/polygon_amoy","https://polygon-amoy.drpc.org","https://rpc-amoy.polygon.technology"]
blast = ["https://rpc.blast.io","https://rpc.ankr.com/blast","https://blast.din.dev/rpc","https://blastl2-mainnet.public.blastapi.io","https://blast.blockpi.network/v1/rpc/public"]
base-sepolia = ["https://sepolia.base.org","https://public.stackup.sh/api/v1/node/base-sepolia","https://base-sepolia-rpc.publicnode.com"]
xchain = https://xchain-rpc.idex.io
plume = https://rpc-plume-mainnet-0.t.conduit.xyz
superposition-testnet = https://testnet-rpc.superposition.so
etherlink-testnet = https://node.ghostnet.etherlink.com
taiko = ["https://rpc.taiko.xyz","https://rpc.taiko.tools","https://rpc.ankr.com/taiko","https://taiko.blockpi.network/v1/rpc/public"]
taiko-testnet = ["https://rpc.hekla.taiko.xyz","https://taiko-hekla.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f","https://rpc.ankr.com/taiko_hekla"]
bitlayer = https://rpc.bitlayer.org
camp-testnet = https://rpc-camp-network-4xje7wy105.t.conduit.xyz
arbitrum-sepolia = ["https://sepolia-rollup.arbitrum.io/rpc","https://sepolia-rollup.arbitrum.io/rpc"]
dexalot-testnet = https://subnets.avax.network/dexalot/testnet/rpc
dexalot = https://subnets.avax.network/dexalot/mainnet/rpc
scroll-testnet = ["https://sepolia-rpc.scroll.io","https://rpc.ankr.com/scroll_sepolia_testnet","https://scroll-sepolia.chainstacklabs.com","https://scroll-testnet-public.unifra.io"]
scroll = ["https://scroll.drpc.org","https://rpc.scroll.io","https://rpc-scroll.icecreamswap.com","https://rpc.ankr.com/scroll","https://scroll-mainnet.chainstacklabs.com"]
xai = https://xai-chain.net/rpc
merlin-testnet = https://testnet-rpc.merlinchain.io
tiltyard = https://subnets.avax.network/tiltyard/mainnet/rpc
sei-testnet = ["https://evm-rpc-arctic-1.sei-apis.com","https://evm-rpc.arctic-1.seinetwork.io"]
hemi-testnet = https://testnet.rpc.hemi.network/rpc
zklink = https://rpc.zklink.io
zklink-testnet = https://sepolia.rpc.zklink.io
loot = https://rpc.lootchain.com/http
zora = https://rpc.zora.energy/
sepolia = ["https://rpc.sepolia.org","https://rpc2.sepolia.org","https://sepolia.drpc.org","https://rpc-sepolia.rockx.com","https://op-sepolia-pokt.nodies.app"]
optimism-sepolia = ["https://sepolia.optimism.io","https://optimism-sepolia.drpc.org","https://endpoints.omniatech.io/v1/op/sepolia/public","https://optimism-sepolia.blockpi.network/v1/rpc/public"]
mp1 = https://maizenet-rpc.usecorn.com
cyber-testnet = ["https://cyber-testnet.alt.technology","https://rpc.testnet.cyber.co"]
blast-testnet = ["https://sepolia.blast.io","https://blast-sepolia.drpc.org","https://blast-sepolia.blockpi.network/v1/rpc/public"]
sophon-testnet = https://rpc.testnet.sophon.xyz
degen = https://rpc.degen.tips
zora-sepolia = https://sepolia.rpc.zora.energy
aurora = ["https://aurora.drpc.org","https://mainnet.aurora.dev"]
aurora-testnet = https://testnet.aurora.dev/
rarible = https://mainnet.rpc.rarichain.org/http
skale-testnet = https://testnet.skalenodes.com/v1/juicy-low-small-testnet
harmony = ["https://harmony-mainnet.chainstacklabs.com","https://api.harmony.one","https://api.s0.t.hmny.io","https://a.api.s0.t.hmny.io","https://rpc.ankr.com/harmony","https://hmyone-pokt.nodies.app"]
harmony-testnet = https://api.s0.ps.hmny.io
skale = https://mainnet.skalenodes.com/v1/elated-tan-skat
xai-testnet = https://testnet-v2.xai-chain.net/rpc
