[rpc_endpoints]
1 = ["https://eth.drpc.org","https://ethereum.publicnode.com","https://eth-mainnet.public.blastapi.io","https://eth.llamarpc.com/rpc/${LLAMANODES_API_KEY}","https://cloudflare-eth.com","https://eth-mainnet.alchemyapi.io/v2/84tGz8xVIWFkagsaSzNjObh7aSPbxeXD","https://eth-mainnet.alchemyapi.io/v2/VsPzIezK0AtqsnrWAuV0Gew-MS7H_E5E","https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}","https://mainnet.infura.io/v3/${INFURA_API_KEY}","https://eth-pokt.nodies.app"]
10 = ["https://optimism.drpc.org","https://mainnet.optimism.io","https://opt-mainnet.g.alchemy.com/v2/3glkhRJRgzHCB2NbDwiQa7G_FTdqn3-T","https://opt-mainnet.g.alchemy.com/v2/7urLa-8k2RR_UYc0exh-b0qg4xySL5KA","https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}","https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://op-pokt.nodies.app"]
14 = ["https://flare.rpc.thirdweb.com","https://rpc.ankr.com/flare"]
25 = ["https://evm.cronos.org","https://evm-dev.cronos.org"]
37 = ["https://dimension-evm-rpc.xpla.dev"]
40 = ["https://mainnet.telos.net/evm"]
41 = ["https://testnet.telos.net/evm"]
47 = ["https://cube-evm-rpc.xpla.dev"]
56 = ["https://bsc.drpc.org","https://bscrpc.com","https://binance.nodereal.io","https://bsc-dataseed.binance.org","https://bsc-dataseed1.binance.org","https://bsc-dataseed2.binance.org","https://bsc-dataseed3.binance.org","https://bsc-dataseed4.binance.org","https://bsc-pokt.nodies.app"]
66 = ["https://exchainrpc.okex.org"]
71 = ["https://evmtestnet.confluxrpc.com"]
81 = ["https://rpc-2.japanopenchain.org:8545","https://rpc-1.japanopenchain.org:8545"]
82 = ["https://rpc.meter.io"]
83 = ["https://rpctest.meter.io"]
88 = ["https://rpc.tomochain.com"]
97 = ["https://data-seed-prebsc-1-s3.binance.org:8545","https://data-seed-prebsc-2-s2.binance.org:8545","https://data-seed-prebsc-1-s1.binance.org:8545","https://data-seed-prebsc-1-s2.binance.org:8545","https://data-seed-prebsc-2-s1.binance.org:8545"]
100 = ["https://gnosis.drpc.org","https://rpc.gnosischain.com","https://rpc.ankr.com/gnosis","https://gnosis-pokt.nodies.app","https://gnosis-mainnet.public.blastapi.io","wss://rpc.gnosischain.com/wss"]
111 = ["https://testnet.rpc.gobob.xyz"]
122 = ["https://rpc.fuse.io","https://fuse-pokt.nodies.app"]
123 = ["https://rpc.fusespark.io"]
137 = ["https://polygon.drpc.org","https://matic-mainnet.chainstacklabs.com","https://polygon-rpc.com","https://polygon.llamarpc.com/rpc/${LLAMANODES_API_KEY}","https://polygon-mainnet.g.alchemy.com/v2/me6Q04fTd2kTT74BUYAp82d_3KL-ObCw","https://polygon-mainnet.g.alchemy.com/v2/q3f-QpPeM_g7rL3G21Cr9tFeuYAquyYl","https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://polygon-pokt.nodies.app","https://polygon-mainnet.infura.io/v3/${INFURA_API_KEY}"]
148 = ["https://json-rpc.evm.shimmer.network"]
155 = ["https://rpc.testnet.tenet.org"]
169 = ["https://pacific-rpc.manta.network/http"]
195 = ["https://testrpc.xlayer.tech"]
196 = ["https://rpc.xlayer.tech"]
204 = ["https://opbnb.drpc.org","https://opbnb-mainnet-rpc.bnbchain.org","https://opbnb.publicnode.com","wss://opbnb.publicnode.com"]
240 = ["https://testnet.zkevm.cronos.org","https://seed.testnet.zkevm.cronos.org"]
250 = ["https://fantom.drpc.org","https://rpc.ftm.tools","https://rpc2.fantom.network","https://rpc3.fantom.network","https://fantom-pokt.nodies.app"]
252 = ["https://rpc.frax.com"]
291 = ["https://rpc.orderly.network","https://l2-orderly-mainnet-0.t.conduit.xyz"]
295 = ["https://mainnet.hashio.io/api"]
296 = ["https://testnet.hashio.io/api"]
300 = ["https://zksync-sepolia.drpc.org","https://sepolia.era.zksync.dev","https://zksync-era-sepolia.blockpi.network/v1/rpc/public"]
324 = ["https://zksync.drpc.org","https://mainnet.era.zksync.io"]
335 = ["https://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/rpc"]
338 = ["https://evm-t3.cronos.org","https://evm-dev-t3.cronos.org"]
388 = ["https://mainnet.zkevm.cronos.org","https://seed.zkevm.cronos.org"]
478 = ["https://rpc.form.network/infra-partner-http"]
480 = ["https://worldchain-mainnet.g.alchemy.com/public"]
592 = ["https://evm.astar.network","https://astar.public.blastapi.io"]
747 = ["https://mainnet.evm.nodes.onflow.org"]
919 = ["https://sepolia.mode.network"]
1001 = ["https://api.baobab.klaytn.net:8651"]
1030 = ["https://evm.confluxrpc.com"]
1075 = ["https://json-rpc.evm.iotaledger.net"]
1088 = ["https://andromeda.metis.io/?owner=1088","https://metis.drpc.org","https://metis-pokt.nodies.app"]
1101 = ["https://zkevm-rpc.com","https://polygon-zkevm.drpc.org"]
1115 = ["https://rpc.test.btcs.network/"]
1116 = ["https://rpc.coredao.org/","https://rpc-core.icecreamswap.com"]
1135 = ["https://rpc.api.lisk.com","https://lisk.drpc.org"]
1284 = ["https://rpc.api.moonbeam.network","wss://wss.api.moonbeam.network"]
1285 = ["https://rpc.api.moonriver.moonbeam.network","wss://wss.api.moonriver.moonbeam.network"]
1287 = ["https://rpc.api.moonbase.moonbeam.network","wss://wss.api.moonbase.moonbeam.network"]
1300 = ["https://mainnet-node.m9.glue.net"]
1329 = ["https://evm-rpc.sei-apis.com"]
1480 = ["https://rpc.islander.vana.org","https://rpc.vana.org"]
1559 = ["https://rpc.tenet.org"]
1625 = ["https://rpc.gravity.xyz"]
1663 = ["https://gobi-rpc.horizenlabs.io/ethv1","https://rpc.ankr.com/horizen_gobi_testnet"]
1811 = ["https://testnet-evm.lif3.com"]
1891 = ["https://replicator.pegasus.lightlink.io/rpc/v1","https://endpoints.omniatech.io/v1/lightlink/pegasus/public"]
1923 = ["https://rpc.ankr.com/swell","https://swell-mainnet.alt.technology"]
1946 = ["https://rpc.minato.soneium.org/"]
1992 = ["https://sanko-arb-sepolia.rpc.caldera.xyz/http"]
1996 = ["https://mainnet.sanko.xyz"]
2037 = ["https://subnets.avax.network/kiwi/testnet/rpc"]
2038 = ["https://subnets.avax.network/shrapnel/testnet/rpc"]
2044 = ["https://subnets.avax.network/shrapnel/mainnet/rpc"]
2221 = ["https://evm.testnet.kava.io","wss://wevm.testnet.kava.io"]
2222 = ["https://kava.drpc.org","https://evm.kava.io","https://evm2.kava.io","wss://wevm.kava.io","wss://wevm2.kava.io","https://kava-pokt.nodies.app"]
2345 = ["https://rpc.goat.network"]
2442 = ["https://polygon-zkevm-cardona.blockpi.network/v1/rpc/public","https://rpc.cardona.zkevm-rpc.com"]
2522 = ["https://rpc.testnet.frax.com"]
2525 = ["https://mainnet.rpc.inevm.com/http"]
2552 = ["https://rpc1.ocean.bahamut.io"]
2741 = ["https://api.raas.matterhosted.dev"]
2810 = ["https://rpc-holesky.morphl2.io"]
2818 = ["https://rpc.morphl2.io"]
3636 = ["https://node.botanixlabs.dev"]
3637 = ["https://rpc.btxtestchain.com"]
3939 = ["https://test.doschain.com"]
4002 = ["https://rpc.testnet.fantom.network/","https://rpc.ankr.com/fantom_testnet","https://fantom-testnet.public.blastapi.io"]
4200 = ["https://merlin.blockpi.network/v1/rpc/public","https://rpc.merlinchain.io"]
4337 = ["https://subnets.avax.network/beam/mainnet/rpc"]
4460 = ["https://l2-orderly-l2-4460-sepolia-8tc3sd7dvy.t.conduit.xyz"]
4801 = ["https://worldchain-sepolia.g.alchemy.com/public"]
5000 = ["https://rpc.mantle.xyz","https://mantle.drpc.org","https://mantle.publicnode.com"]
5115 = ["https://rpc.testnet.citrea.xyz"]
5611 = ["https://opbnb-testnet-rpc.bnbchain.org"]
6001 = ["https://fullnode-mainnet.bouncebitapi.com"]
6342 = ["https://carrot.megaeth.com/rpc"]
7560 = ["https://cyber.alt.technology","https://rpc.cyber.co"]
7700 = ["https://canto.slingshot.finance","https://canto.neobase.one","https://mainnode.plexnode.org:8545"]
7701 = ["https://testnet-archive.plexnode.wtf"]
7979 = ["https://main.doschain.com"]
8217 = ["https://public-node-api.klaytnapi.com/v1/cypress","https://klaytn-pokt.nodies.app"]
8227 = ["https://subnets.avax.network/space/mainnet/rpc"]
8453 = ["https://base.drpc.org","https://mainnet.base.org","https://base.meowrpc.com","https://base-pokt.nodies.app","https://base.blockpi.network/v1/rpc/public"]
8822 = ["https://json-rpc.evm.iotaledger.net"]
10081 = ["https://rpc-1.testnet.japanopenchain.org:8545","https://rpc-2.testnet.japanopenchain.org:8545"]
10200 = ["https://rpc.chiadochain.net","https://rpc.chiado.gnosis.gateway.fm","wss://rpc.chiadochain.net/wss","https://gnosis-chiado.publicnode.com","wss://gnosis-chiado.publicnode.com"]
10888 = ["https://rpc-gs-testnet.gameswift.io","https://rpc-testnet.gameswift.io"]
11501 = ["https://rpc-mainnet-1.bevm.io/","https://rpc-mainnet-2.bevm.io/"]
13337 = ["https://subnets.avax.network/beam/testnet/rpc"]
14800 = ["https://rpc.moksha.vana.org"]
17000 = ["https://rpc.holesky.ethpandaops.io","https://ethereum-holesky.publicnode.com","wss://ethereum-holesky.publicnode.com"]
18233 = ["https://rpc.unreal-orbit.gelato.digital"]
19011 = ["https://rpc.mainnet.oasys.homeverse.games"]
33111 = ["https://curtis.rpc.caldera.xyz/http"]
34443 = ["https://mainnet.mode.network","https://1rpc.io/mode"]
40875 = ["https://rpc.testnet.oasys.homeverse.games"]
41923 = ["https://rpc.edu-chain.raas.gelato.cloud"]
42161 = ["https://arbitrum.drpc.org","https://arb1.arbitrum.io/rpc","https://arb-mainnet.g.alchemy.com/v2/N71NRfHZGk2jbnDkW-GiM6fTe6ysJOmp","https://arb-mainnet.g.alchemy.com/v2/KhVdIItVH0ttiQvBYYO5NPL-De-gLWoW","https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}","https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}","https://arb-pokt.nodies.app"]
42170 = ["https://arbitrum-nova.drpc.org","https://nova.arbitrum.io/rpc"]
42220 = ["https://celo.drpc.org","https://forno.celo.org","wss://forno.celo.org/ws"]
42793 = ["https://node.mainnet.etherlink.com","https://etherlink-mainnet-pub-l5p9tu.zeeve.net/rpc"]
43113 = ["https://api.avax-test.network/ext/bc/C/rpc","https://rpc.ankr.com/avalanche_fuji"]
43114 = ["https://avalanche.drpc.org","https://api.avax.network/ext/bc/C/rpc","https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}","https://avax-pokt.nodies.app/ext/bc/C/rpc"]
44787 = ["https://alfajores-forno.celo-testnet.org","wss://alfajores-forno.celo-testnet.org/ws"]
48899 = ["https://zircuit1.p2pify.com"]
48900 = ["https://zircuit-mainnet.drpc.org","https://mainnet.aurora.dev"]
53935 = ["https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc"]
55244 = ["https://rpc.superposition.so"]
59141 = ["https://linea-sepolia.blockpi.network/v1/rpc/public","https://rpc.sepolia.linea.build","https://linea-sepolia.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"]
59144 = ["https://linea.drpc.org","https://rpc.linea.build","wss://rpc.linea.build","https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}","wss://linea-mainnet.infura.io/ws/v3/${INFURA_API_KEY}"]
59902 = ["https://sepolia.metisdevops.link"]
60808 = ["https://rpc.gobob.xyz","https://bob-mainnet.blastapi.io/278bd36b-e02e-4391-a2b6-54e68e6695fd"]
64002 = ["https://xchain-testnet-rpc.idex.io"]
80002 = ["https://rpc.ankr.com/polygon_amoy","https://polygon-amoy.drpc.org","https://rpc-amoy.polygon.technology"]
81457 = ["https://rpc.blast.io","https://rpc.ankr.com/blast","https://blast.din.dev/rpc","https://blastl2-mainnet.public.blastapi.io","https://blast.blockpi.network/v1/rpc/public"]
84532 = ["https://sepolia.base.org","https://public.stackup.sh/api/v1/node/base-sepolia","https://base-sepolia-rpc.publicnode.com"]
94524 = ["https://xchain-rpc.idex.io"]
98865 = ["https://rpc-plume-mainnet-0.t.conduit.xyz"]
98985 = ["https://testnet-rpc.superposition.so"]
128123 = ["https://node.ghostnet.etherlink.com"]
167000 = ["https://rpc.taiko.xyz","https://rpc.taiko.tools","https://rpc.ankr.com/taiko","https://taiko.blockpi.network/v1/rpc/public"]
167009 = ["https://rpc.hekla.taiko.xyz","https://taiko-hekla.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f","https://rpc.ankr.com/taiko_hekla"]
200901 = ["https://rpc.bitlayer.org"]
325000 = ["https://rpc-camp-network-4xje7wy105.t.conduit.xyz"]
421614 = ["https://sepolia-rollup.arbitrum.io/rpc","https://sepolia-rollup.arbitrum.io/rpc"]
432201 = ["https://subnets.avax.network/dexalot/testnet/rpc"]
432204 = ["https://subnets.avax.network/dexalot/mainnet/rpc"]
534351 = ["https://sepolia-rpc.scroll.io","https://rpc.ankr.com/scroll_sepolia_testnet","https://scroll-sepolia.chainstacklabs.com","https://scroll-testnet-public.unifra.io"]
534352 = ["https://scroll.drpc.org","https://rpc.scroll.io","https://rpc-scroll.icecreamswap.com","https://rpc.ankr.com/scroll","https://scroll-mainnet.chainstacklabs.com"]
660279 = ["https://xai-chain.net/rpc"]
686868 = ["https://testnet-rpc.merlinchain.io"]
710420 = ["https://subnets.avax.network/tiltyard/mainnet/rpc"]
713715 = ["https://evm-rpc-arctic-1.sei-apis.com","https://evm-rpc.arctic-1.seinetwork.io"]
743111 = ["https://testnet.rpc.hemi.network/rpc"]
810180 = ["https://rpc.zklink.io"]
810181 = ["https://sepolia.rpc.zklink.io"]
5151706 = ["https://rpc.lootchain.com/http"]
7777777 = ["https://rpc.zora.energy/"]
11155111 = ["https://rpc.sepolia.org","https://rpc2.sepolia.org","https://sepolia.drpc.org","https://rpc-sepolia.rockx.com","https://op-sepolia-pokt.nodies.app"]
11155420 = ["https://sepolia.optimism.io","https://optimism-sepolia.drpc.org","https://endpoints.omniatech.io/v1/op/sepolia/public","https://optimism-sepolia.blockpi.network/v1/rpc/public"]
21000000 = ["https://maizenet-rpc.usecorn.com"]
111557560 = ["https://cyber-testnet.alt.technology","https://rpc.testnet.cyber.co"]
168587773 = ["https://sepolia.blast.io","https://blast-sepolia.drpc.org","https://blast-sepolia.blockpi.network/v1/rpc/public"]
531050104 = ["https://rpc.testnet.sophon.xyz"]
666666666 = ["https://rpc.degen.tips"]
999999999 = ["https://sepolia.rpc.zora.energy"]
1313161554 = ["https://aurora.drpc.org","https://mainnet.aurora.dev"]
1313161555 = ["https://testnet.aurora.dev/"]
1380012617 = ["https://mainnet.rpc.rarichain.org/http"]
1444673419 = ["https://testnet.skalenodes.com/v1/juicy-low-small-testnet"]
1666600000 = ["https://harmony-mainnet.chainstacklabs.com","https://api.harmony.one","https://api.s0.t.hmny.io","https://a.api.s0.t.hmny.io","https://rpc.ankr.com/harmony","https://hmyone-pokt.nodies.app"]
1666900000 = ["https://api.s0.ps.hmny.io"]
2046399126 = ["https://mainnet.skalenodes.com/v1/elated-tan-skat"]
37714555429 = ["https://testnet-v2.xai-chain.net/rpc"]
